#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LiftPotentiometer, sensorPotentiometer)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  SkyriseClaw,        sensorDigitalOut)
#pragma config(Sensor, I2C_1,  LeftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  RightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           LFDrive,       tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           LBDrive,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port3,           LCLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LTLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LIntake,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RIntake,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RCLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RTLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RBDrive,       tmotorVex393HighSpeed_MC29, openLoop, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port10,          RFDrive,       tmotorVex393HighSpeed_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
 
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "SensorValues.h"   //Sensor values for potentiometer, gyro, and encoders
#include "AutonomousFunctions.h"   //Predefined functions for autonomous and user control
#include "AutonomousPrograms.h"   //Code for autonomous programs
#include "UserControl.h"   //Code for teleop

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
	nMotorEncoder[LBDrive] = 0;
	nMotorEncoder[RBDrive] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	RunAuton();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	TeleOp();
}
