//#pragma config(Sensor, in2,    gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool  gyro_valid = false;
float gyro_angle;

task runGyro() {
	int realBias;
	int value;
	float angle;
	float offsetAngle;
	SensorType[gyro] = sensorNone;
	wait1Msec(500);
	SensorType[gyro]= sensorGyro;
	wait10Msec(50);
	realBias = SensorBias[gyro];
	SensorBias[gyro] = SensorBias[gyro] - 1000;

	wait10Msec(100);

	SensorScale[gyro] = 130;

	offsetAngle =  SensorValue[gyro];
	while(true){
		value = SensorValue[gyro];

		// Create float angle, remove offset
		angle = (value - offsetAngle) / 10.0;

		// normalize into the range 0 - 360
		if( angle < 0 )
			angle += 360;

		// put in global for display
		gyro_angle = angle;

		// We can use the angle
		gyro_valid = true;

		// Delay
		wait1Msec( 20 );
		//writeDebugStreamLine("Angle %f", gyro_angle);
	}
}
/*task main(){
startTask(runGyro);
while(true){
writeDebugStreamLine("Angle %f", gyro_angle);
}
} */
